<?php


namespace frontend\controllers;

use frontend\forms\NewResponseForm;
use frontend\models\Response;
use frontend\models\Task;
use frontend\models\User;
use frontend\services\CreateResponse;
use yii\web\Controller;
use Yii;

class ResponseController extends BaseController
{

    protected $response;
    protected $target_user;

    public function __construct($id, $module, $config = [])
    {

        $this->response = Response::findOne(['id' => Yii::$app->request->get('id')]);
        $this->target_user = User::findOne(['id' => Yii::$app->user->id]);
        parent::__construct($id, $module, $config);
    }

    /***
     * @param \yii\base\Action $action
     * @return bool
     * @throws \yii\web\BadRequestHttpException
     */

    public function beforeAction($action)
    {
        if ($this->response === null) {
            Yii::$app->session->setFlash('error', 'Такого отклика не найдено');
            Yii::$app->response->redirect('/tasks/');
        } else {
            return parent::beforeAction($action);
        }
        return false; // TODO: Change the autogenerated stub
    }

    public function actionNew($id)
    {
        $task = Task::findOne(['id' => $id]);
        $form = new NewResponseForm();
        $response = new CreateResponse(new Response());
        $request = Yii::$app->request->post();

        if ($form->load($request)) {
            $response->getObject()->setAttributes($request['NewResponseForm']);

            try {
                $response->addNewResponse($task, $this->target_user);

                Yii::$app->session->setFlash('success', 'Вы откликнулись на задание  "' . $task->title . '"');
                $this->redirect('/tasks/view/' . $task->id);
            } catch (\Exception $e) {
                Yii::$app->session->setFlash('error', $e->getMessage());
                $this->redirect('/tasks/view/' . $task->id);
            }
        }
    }

    public function actionCancel()
    {
        $response = new CreateResponse($this->response);

        try {
            $response->refuseResponse($this->target_user);

            Yii::$app->session->setFlash('success', 'Вы отказали  ' . $response->getObject()->user->full_name . '  в выполнении задания');
            $this->redirect('/tasks/view/' . $response->getObject()->task->id);
        } catch (\Exception $e) {
            Yii::$app->session->setFlash('error', $e->getMessage());
            $this->redirect('/tasks/view/' . $response->getObject()->task->id);
        }
    }
}
