<?php


namespace frontend\controllers;

use frontend\forms\NewResponseForm;
use frontend\models\Response;
use frontend\models\Task;
use frontend\models\User;
use frontend\services\CreateResponse;
use Yii;
use yii\base\Action;
use yii\web\BadRequestHttpException;
use yii\web\NotFoundHttpException;
use yii\helpers\Url;

class ResponseController extends BaseController
{

    /**
     * @var Response $response
     */
    protected $response;

    /**
     * @var User $currentUser
     */
    protected $currentUser;

    /**
     * @param Action $action
     * @return bool
     * @throws BadRequestHttpException
     * @throws NotFoundHttpException
     */

    public function beforeAction($action)
    {
        if (Yii::$app->request->get('id') && Yii::$app->request->get('id') !== null) {
            $this->response = Response::findOrFail(['id' => Yii::$app->request->get('id')]);
        }

        $this->currentUser = Yii::$app->user->identity;

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    public function actionNew($id)
    {
        $task = Task::findOne(['id' => $id]);
        $form = new NewResponseForm();
        $response = new CreateResponse(new Response());
        $request = Yii::$app->request->post();

        if ($form->load($request)) {
            $response->getObject()->setAttributes($request['NewResponseForm']);

            try {
                $response->addNewResponse($task, $this->currentUser);

                Yii::$app->session->setFlash('success', 'Вы откликнулись на задание  "' . $task->title . '"');
                $this->redirect('/tasks/view/' . $task->id);
            } catch (\Exception $e) {
                Yii::$app->session->setFlash('error', $e->getMessage());
                $this->redirect('/tasks/view/' . $task->id);
            }
        }
    }

    public function actionCancel()
    {
        try {
            Response::blockedResponse($this->response ,$this->currentUser);
            Yii::$app->session->setFlash('success', 'Вы отказали  ' . $this->response->user->full_name . '  в выполнении задания');
            $this->redirect(Url::to(['/tasks/view', 'id' => $this->response->task->id]));
        } catch (\Exception $e) {
            Yii::$app->session->setFlash('error', $e->getMessage());
            $this->redirect('/tasks/view/' . $this->response->task->id);
        }
    }
}
