<?php

namespace common\models;

use frontend\forms\PhotoJobForm;
use Yii;
use yii\db\ActiveQuery;
use yii\db\ActiveRecord;
use yii\db\Exception;

/**
 * This is the model class for table "photo_job".
 *
 * @property int $id
 * @property int|null $user_id
 * @property string|null $img
 * @property string|null $created_at
 * @property string|null $updated_at
 *
 * @property User $user
 */
class PhotoJob extends ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'photo_job';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id'], 'integer'],
            [['created_at', 'updated_at'], 'safe'],
            [['img'], 'string', 'max' => 255],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'img' => 'Img',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::class, ['id' => 'user_id']);
    }

    public function init()
    {
        $this->user_id = Yii::$app->user->id;
        parent::init(); // TODO: Change the autogenerated stub
    }

    public static function createNewPhotoJob(PhotoJobForm $form): bool
    {
        $item = new self();
        $item->attributes = $form->attributes;

        if ($item->save()) {
            return true;
        } else {
            throw new Exception('Photo not saved');
        }
    }
}
