<?php

namespace frontend\models;

use Yii;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "user".
 *
 * @property int $id
 * @property string $full_name
 * @property string|null $email
 * @property int|null $role_id
 * @property int|null $city_id
 * @property int|null $user_status_id
 * @property string $date_birth
 * @property string|null $about
 * @property string $password
 * @property int|null $tel
 * @property string|null $skype
 * @property string|null $messenger
 * @property double $rating
 * @property string $created_at
 * @property string $updated_at
 *
 * @property Comment[] $comments
 * @property Message[] $messages
 * @property Message[] $messages0
 * @property Response[] $responses
 * @property Task[] $tasks
 * @property Task[] $tasks0
 * @property Role $role
 * @property City $city
 * @property UserStatus $userStatus
 */
class User extends \yii\db\ActiveRecord implements IdentityInterface
{
    public const ADMIN = 1;
    public const CUSTOMER = 2;
    public const EXECUTOR = 3;
    public const MAX_RATING = 5;
    public const RATING_DEFAULT = 0;

    public function init()
    {
        $this->rating = self::RATING_DEFAULT;
        parent::init(); // TODO: Change the autogenerated stub
    }

    public $password_repeat;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user';
    }

   public static function findIdentity($id)
    {
        return self::findOne($id);
    }

    public static function findIdentityByAccessToken($token, $type = null)
    {
        // TODO: Implement findIdentityByAccessToken() method.
    }

    public function getId()
    {
        return $this->getPrimaryKey();
    }

    public function getAuthKey()
    {
        // TODO: Implement getAuthKey() method.
    }

    public function validateAuthKey($authKey)
    {
        // TODO: Implement validateAuthKey() method.
    }

    public function validatePassword($password)
    {
        return \Yii::$app->getSecurity()->validatePassword($password, $this->password);
    }

    public function setHash()
    {
        $this->password = \Yii::$app->getSecurity()->generatePasswordHash($this->password);
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['full_name', 'password', 'rating'], 'required'],
            [['role_id', 'city_id', 'user_status_id'], 'integer'],
            [['date_birth', 'created_at', 'updated_at', 'rating'], 'safe'],
            [['about'], 'string'],
            [['full_name', 'email', 'password', 'skype', 'messenger'], 'string', 'max' => 255],
            [['email'], 'unique'],
            [['role_id'], 'exist', 'skipOnError' => true, 'targetClass' => Role::class, 'targetAttribute' => ['role_id' => 'id']],
            [['city_id'], 'exist', 'skipOnError' => true, 'targetClass' => City::class, 'targetAttribute' => ['city_id' => 'id']],
            [['user_status_id'], 'exist', 'skipOnError' => true, 'targetClass' => UserStatus::class, 'targetAttribute' => ['user_status_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'full_name' => 'Full Name',
            'email' => 'Email',
            'role_id' => 'Role ID',
            'city_id' => 'City ID',
            'user_status_id' => 'User Status ID',
            'date_birth' => 'Date Birth',
            'about' => 'About',
            'password' => 'Password',
            'phone' => 'Phone',
            'skype' => 'Skype',
            'rating' => 'Rating',
            'messenger' => 'Messenger',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategoryExecutors()
    {
        return $this->hasMany(CategoryExecutor::class, ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getComments()
    {
        return $this->hasMany(Comment::class, ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMessages()
    {
        return $this->hasMany(Message::class, ['sender' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMessages0()
    {
        return $this->hasMany(Message::class, ['recipient' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getResponses()
    {
        return $this->hasMany(Response::class, ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTasks()
    {
        return $this->hasMany(Task::class, ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTasks0()
    {
        return $this->hasMany(Task::class, ['executor_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getRole()
    {
        return $this->hasOne(Role::class, ['id' => 'role_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCity()
    {
        return $this->hasOne(City::class, ['id' => 'city_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUserStatus()
    {
        return $this->hasOne(UserStatus::class, ['id' => 'user_status_id']);
    }

    /**
     * @return bool
     */

    public function isAdmin()
    {
        return $this->role_id === self::ADMIN;
    }

    /**
     * @return bool
     */

    public function isCustomer()
    {
        return $this->role_id === self::CUSTOMER;
    }

    /**
     * @return bool
     */

    public function isExecutor()
    {
        return $this->role_id === self::EXECUTOR;
    }

   public function setRating($rating)
   {
       $this->rating = $rating;

       if (!$this->save()) {
           throw new \Exception('Рейтинг не обновлен');
       }
   }
}
