<?php


namespace frontend\src\status;

use frontend\models\Task;
use frontend\src\exceptions\StatusException;
use Yii;

class CancelAction extends AvailableActions
{
    protected $roles = [self::ROLE_ADMIN, self::ROLE_CUSTOMER];
    protected $next_status = self::STATUS_CANCEL;
    protected $access_statuses = [self::STATUS_PUBLIC];

    public function setNextStatus()
    {
        if(!$this->task->isUserOwner($this->target_user)) {
            throw new StatusException('Вы не владелец текщего задания');
        }

        parent::setNextStatus(); // TODO: Change the autogenerated stub
    }

    public function apply(): void
    {
        $this->setNextStatus();
        $this->task->save();
    }
}
